"""update masjid table again

Revision ID: c21d88e6613e
Revises: 3db8041de2d3
Create Date: 2025-04-25 13:04:23.295542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c21d88e6613e'
down_revision: Union[str, None] = '3db8041de2d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('masajid', sa.Column('latitude', sa.Float(), nullable=False))
    op.add_column('masajid', sa.Column('longitude', sa.Float(), nullable=False))
    op.drop_column('masajid', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('masajid', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('masajid', 'longitude')
    op.drop_column('masajid', 'latitude')
    # ### end Alembic commands ###
