"""create masjid table

Revision ID: f81278227b32
Revises: 
Create Date: 2025-04-21 14:43:18.213393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f81278227b32'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('masjid',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('fjr', sa.Time(), nullable=True),
    sa.Column('zuhr', sa.Time(), nullable=True),
    sa.Column('asr', sa.Time(), nullable=True),
    sa.Column('maghrib', sa.Time(), nullable=True),
    sa.Column('isha', sa.Time(), nullable=True),
    sa.Column('jumma', sa.Time(), nullable=False),
    sa.Column('have_washroom', sa.Boolean(), nullable=True),
    sa.Column('have_wuzu_area', sa.Boolean(), nullable=True),
    sa.Column('capacity', sa.String(), nullable=True),
    sa.Column('school', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.drop_table('masjid')
    # ### end Alembic commands ###
